services:
  anyskin_ros2_base:
    image: anyskin_ros2:base
    build:
      context: .
      target: base
      args:
        ROS_DISTRO: humble
    container_name: anyskin_ros2_base_container

    network_mode: "host"
    ipc: "host"
    pid: "host"
    privileged: true

    command: /bin/bash
    tty: true
    stdin_open: true

    volumes:
      - $HOME/.Xauthority:/root/.Xauthority 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw 
      - /dev:/dev

    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 100
      RCUTILS_COLORIZED_OUTPUT: 1
      SHELL: /bin/bash

    cap_add:
      - SYS_NICE

    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856

  anyskin_ros2_overlay:
    extends: anyskin_ros2_base
    image: anyskin_ros2:overlay
    build:
      context: .
      target: overlay
    container_name: anyskin_ros2_overlay_container

  anyskin_ros2_magnitude_broadcaster:
    extends: anyskin_ros2_overlay
    container_name: anyskin_ros2_overlay_container
    command: >
      bash -c "source /opt/ros/$ROS_DISTRO/setup.bash &&
      source install/setup.bash &&
      ros2 run anyskin_ros2_bringup tactile_sensor_broadcaster"
